Update Control Message Tag Bits
aws/aws-ofi-nccl pull request #120
Opened 2022-06-23 21:17 UTC by jdinan

*Issue #, if available:*

No issue logged.

*Description of changes:*

The `max_tag` bitmask indicates which bits that can be used in a user tag. The next highest bit is used to denote a control message. Presently, the control message bit is set by OR'ing the negation of `max_tag`. However, this also sets the ignored bits and some providers flag this as an error. This patch sets only the control message bit in the tag.

There also is a minor update to the Makefile to allow setting `CC` used to build the tests. This is needed on systems where `CC=cc` is used to build MPI code.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-24 16:14 UTC, bwbarrett approved these changes

2022-06-25 05:15 UTC, rashikakheria requested changes
We would also require similar change in L #974 below

```
uint64_t control_bit_mask = ~(nccl_ofi_comp->max_tag);
```

to ensure that we only check for the control bit (not the ignored bits).

2022-06-25 05:17 UTC, rashikakheria commented
Thanks James for your contribution. Could you also sign your commits as mentioned here: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification ? This is required to merge any PRs to our repository.

2022-06-25 16:14 UTC, jdinan commented
@rashikakheria Good catch! I made that update and signed all of the commits. 🙇‍♂️

2022-06-27 04:08 UTC, rashikakheria approved these changes

2022-06-27 04:08 UTC, merged