build: Introduce flag to build with UBSAN
aws/aws-ofi-nccl pull request #249
Opened 2023-08-22 22:41 UTC by maxtmann

UBSAN (Undefined Behavior Sanitizer) is a useful tool to catch code usage that results in undefined behavior.

Such as array subscript out of bounds (where the bounds can be statically determined), bitwise shifts that are out of bounds for their data type, dereferencing misaligned or null pointers, signed integer overflow and etc.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-22 22:43 UTC, rauteric approved these changes

2023-08-23 03:16 UTC, bwbarrett requested changes

2023-08-23 03:16 UTC, bwbarrett commented on configure.ac
> +CHECK_ENABLE_UBSAN()
Since this is a compiler feature, it should really be around line 37.  But definitely not in between two checks for external packages.

2023-08-23 03:16 UTC, bwbarrett commented on m4/check_enable_ubsan.m4
> +  AS_IF([test "${enable_ubsan}" = "yes"],
you should run a test compile of a simple application to ensure that -fsanitize=undefined actually works with this compiler.

2023-08-30 21:05 UTC, bwbarrett commented
@maxtmann is this still necessary with #265, or should it be closed?

2023-08-30 21:37 UTC, closed without merging