Fail if GDR support is disabled on supported instances
aws/aws-ofi-nccl pull request #286
Opened 2023-10-11 20:54 UTC by rauteric

Running without GDR on P4+ instances is not currently supported, so fail in this case.

Also, warn if setting `FI_OPT_CUDA_API_PERMITTED=false` fails, forcing fallback to non-GDR.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-11 21:16 UTC, bwbarrett requested changes

2023-10-11 21:16 UTC, bwbarrett commented on src/platform-aws.c
> +	bool gdr_supported;
Consider naming this `gdr_required` to express the intent.  This name leaves some confusion on whether or not the flag must be true for gdr to work, which isn't what the code does.

2023-10-11 21:16 UTC, bwbarrett commented on src/platform-aws.c
> +	struct ec2_platform_data *platform_data = get_platform_data();
Provide an environment variable to skip this check.

2023-10-11 21:16 UTC, bwbarrett commented on src/nccl_ofi_net.c
> +				NCCL_OFI_WARN("Could not disable CUDA API usage for HMEM, disabling GDR");
I don't think this should be a warn.  I think info is right.  Otherwise, this warning is going to pop on every run on the P3dn and G* platforms.

2023-10-12 02:47 UTC, bwbarrett requested changes

2023-10-12 02:47 UTC, bwbarrett commented on include/nccl_ofi_param.h
> +OFI_NCCL_PARAM_INT(disable_required_gdr_check, "DISABLE_REQUIRED_GDR_CHECK", 0);
GDR_REQUIRED.  This sounds like disabling a required check for GDR, not disabling the check if gdr should be required.

2023-10-12 03:28 UTC, rauteric commented on README.md
> +      </td>
Nit: extra `</td>`

2023-10-12 03:29 UTC, bwbarrett submitted a review, later dismissed

2023-10-12 03:30 UTC, bwbarrett approved these changes

2023-10-12 17:17 UTC, merged