Documentation updates
aws/aws-ofi-nccl pull request #334
Opened 2024-02-15 17:21 UTC by rajachan

See individual commit messages for details.

Some more updates are needed to the README.md, which will come in a following PR.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-15 17:23 UTC, bwbarrett commented
Sorry, I didn't see this before I did some long standing doc update work.  We shouldn't treat master docs like release docs, because it confuses our customers and leaders.  But let's target this patch (minus the code owners, which is better than mine and I'll drop mine) to the v1.8.x branch you're about to create.

2024-02-15 17:28 UTC, bwbarrett requested changes
Looks good, other than retarget to the 1.8.x branch.

2024-02-15 17:28 UTC, bwbarrett commented on INSTALL.md
> +building from source for production uses..
double period.

2024-02-15 17:28 UTC, bwbarrett commented on INSTALL.md
> +`aws-ofi-nccl` requires a working installation of Libfabric. You can
we should specify a version here.  And note that the version required is different on EFA than other providers.

2024-02-15 18:22 UTC, rauteric commented on INSTALL.md
> +  --with-cuda=PATH        Path to non-standard CUDA installation
Shouldn't we update this, as the path is ignored now?

2024-02-16 06:33 UTC, closed without merging

2024-02-16 06:33 UTC, rajachan commented
Closing to rework on top of #335