rdma: support NCCL multi-recv interface
aws/aws-ofi-nccl pull request #348
Opened 2024-02-22 00:17 UTC by rauteric

The multi-recv interface allows aggregating up to 8 receive requests in a single request. The changes include msgbuff changes to be tag-aware.

* Temporarily disables eager; it will be re-enabled in a future commit.
* Makes `connect()` blocking; we need to better understand why this is necessary.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-22 00:22 UTC, rauteric commented on include/nccl_ofi.h
> +	uintptr_t l_comm_ptr;
Oops, leftover debugging. Will get rid of this.

2024-02-22 00:22 UTC, rauteric commented on include/nccl_ofi_rdma.h
> +	uintptr_t s_comm_ptr;
Leftover debugging

2024-02-22 00:22 UTC, rauteric commented on src/nccl_ofi_api.c
> +//_Static_assert(offsetof(nccl_net_ofi_conn_handle_t, state) <= NCCL_NET_HANDLE_MAXSIZE_V4,
Wasn't sure why we still need this `Static_assert`. Do we need to deprecate support for plugin interface v4?

2024-02-22 00:26 UTC, rauteric commented on src/nccl_ofi_api.c
> +//_Static_assert(offsetof(nccl_net_ofi_conn_handle_t, state) <= NCCL_NET_HANDLE_MAXSIZE_V4,
Sorry, actually the only reason I needed to make the handle bigger was to add some debug info, so we shouldn't need to get rid of this assert at all. Will fix.

2024-02-22 22:29 UTC, bwbarrett requested changes

2024-02-24 01:33 UTC, rauteric commented
Addressed the major points of Brian's review: splitting into more commits and removing abstraction-breaking changes from msgbuff.

Some stylistic things are still WIP.

2024-02-25 20:07 UTC, rauteric commented
"Fixed" hang in ring unit test: [9207e74](https://github.com/aws/aws-ofi-nccl/pull/348/commits/9207e74b36ad6a492c0f29692ea381387f91a7f2)

2024-06-03 16:53 UTC, a-szegel commented
Please merge master.

2024-10-02 20:33 UTC, rauteric commented
Going to close this PR for now. This branch will need to be rebased, and we need to address the perf issues here before adding this feature.

2024-10-02 20:33 UTC, closed without merging