Functional tests try all devices instead of just one random device
aws/aws-ofi-nccl pull request #349
Opened 2024-02-22 02:32 UTC by AmedeoSapio

Currently, functional tests are selecting one random device and testing that device only, so bugs that affect a single specific device (e.g., device 0) may pass unnoticed. 
This PR is removing the random selection and instead runs each test for all devices.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-22 16:55 UTC, bwbarrett requested changes
Your commit message should be something like tests: Make message_transfer test all devices. You want to clearly highlight the change in an active voice.

2024-02-22 16:55 UTC, bwbarrett commented on tests/functional/nccl_message_transfer.c
> +	assert(sizes != NULL);
don't assume asserts are enabled.

2024-02-22 16:55 UTC, bwbarrett commented on tests/functional/nccl_message_transfer.c
> +	char handle[NCCL_NET_HANDLE_MAXSIZE];
There are a bunch of changes in this commit that are reorganizing code and unrelated to the core purpose of this commit (changing the device id handling).  Please move those into their own commits (at least one for hoisting variables to the top of the function and another for moving iterator declarations into the for loop, possibly more but use your judgement).

2024-03-02 18:30 UTC, rauteric approved these changes

2024-03-04 16:30 UTC, bwbarrett approved these changes

2024-03-04 17:19 UTC, merged