tuner: Fix missing config.h include
aws/aws-ofi-nccl pull request #362
Opened 2024-03-14 20:45 UTC by rajachan

Without this, we were incorrectly including neuron headers instead of CUDA ones when HAVE_CUDA was not defined. Also fail compilation if neither definition was found rather than having a fall-through case.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-03-14 20:57 UTC, bwbarrett commented on include/nccl-headers/error.h
>  #include "nccl-headers/neuron/error.h"
Nothing sane will happen in the third case; add an else case that `#error`s.

2024-03-14 20:58 UTC, aws-nslick approved these changes
Note that https://github.com/aws/aws-ofi-nccl/pull/351/ has the same fix and integrates with clang-tidy to prevent this in perpetuity.

2024-03-14 21:09 UTC, aws-nslick commented
Why did this pass distcheck given the unguarded usage of ncclInvalidUsage [here](https://github.com/rajachan/aws-ofi-nccl/blob/missing-config-stop-relying-on-getting-lucky/src/tuner/nccl_ofi_tuner.c#L24)?

2024-03-15 04:09 UTC, rauteric commented
> Why did this pass distcheck given the unguarded usage of ncclInvalidUsage [here](https://github.com/rajachan/aws-ofi-nccl/blob/missing-config-stop-relying-on-getting-lucky/src/tuner/nccl_ofi_tuner.c#L24)?

I think it's because `nccl_ofi_tuner.c` includes `nccl-headers/nvidia/tuner.h` (which includes `nccl-headers/net.h` which includes `nccl-headers/neuron/net.h` which includes `nccl-headers/neuron/error.h`) before including `nccl_ofi_tuner.h` (which includes `config.h` which defines `HAVE_CUDA`) 🙃🙃🙃 

tl;dr `nccl_ofi_tuner.c` should include `nccl_ofi_tuner.h` first.

2024-03-15 15:41 UTC, bwbarrett commented
> tl;dr `nccl_ofi_tuner.c` should include `nccl_ofi_tuner.h` first.

Incorrect.  The first include in any `.c` file should be `#include "config.h"`.  I missed this in CR, but that needs to be fixed.

2024-03-26 17:58 UTC, bwbarrett requested changes

2024-03-26 17:58 UTC, bwbarrett commented on include/nccl_ofi_tuner.h
> +#include "config.h"
config.h should be the first include, before even system header files.

2024-03-30 13:43 UTC, bwbarrett submitted a review, later dismissed

2024-03-30 15:07 UTC, bwbarrett commented
The failure looks like a real issue:
```
In file included from ../include/nccl-headers/nvidia/tuner.h:12,
                 from tuner/nccl_ofi_model.c:3:
../include/nccl-headers/error.h:13:2: error: #error "Neither CUDA nor Neuron support is available"
   13 | #error "Neither CUDA nor Neuron support is available"
      |  ^~~~~
make[2]: *** [Makefile:559: tuner/nccl_ofi_model.lo] Error 1
make[1]: *** [Makefile:439: all-recursive] Error 1
make: *** [Makefile:371: all] Error 2
```

2024-03-30 18:20 UTC, AmedeoSapio approved these changes

2024-03-31 02:35 UTC, merged