Changes to support the v8 interface of the NCCL plugin interface
aws/aws-ofi-nccl pull request #365
Opened 2024-03-21 19:00 UTC by rajachan

A more succint version of https://github.com/aws/aws-ofi-nccl/pull/345 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-03-21 19:15 UTC, rauteric requested changes

2024-03-21 19:16 UTC, rajachan commented on include/nccl_ofi.h
> +
silly yank-put, fixed.

2024-03-21 19:16 UTC, rauteric approved these changes

2024-03-26 17:56 UTC, bwbarrett approved these changes

2024-03-26 17:56 UTC, bwbarrett commented on src/nccl_ofi_api.c
> +	return nccl_net_ofi_regMr(comm, data, (size_t)size, type, mhandle);
you don't actually need the explicit cast here, but it also does no harm.

2024-03-30 13:41 UTC, merged