fix: libcuda: resolve transiently
aws/aws-ofi-nccl pull request #374
Opened 2024-04-04 03:25 UTC by aws-nslick

1. cleans up cuda usage by constraining all cuda calls behind inline functions in nccl_ofi_cuda.h, and make nccl_ofi_cuda.h safe to include on neuron builds. Avoid calling cuPointerGetAttribute twice on all pointer-to-device calls by using the plural api.

2. dlopen/dlsym calls for libcuda.so are replaced with weak symbols, and all usages are guarded by null checks.

At runtime, our resolution of libfabric pulls in the symbols, which can be confirmed with eg: `LD_DEBUG=all ./bin/cuda_check'.

This fixes containerized plugin builds where only cudatoolkit is resolvable and the driver is not present.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-04-04 03:47 UTC, bwbarrett requested changes

2024-04-04 03:47 UTC, bwbarrett commented on include/nccl_ofi_cuda.h
> +static inline int nccl_net_ofi_get_cuda_device(void *data, int *dev_id)
why static inline?  This seems like overkill.

I see no benefit to making this file includable with the Neuron build; it just adds complexity better handled elsewhere.

2024-04-04 03:47 UTC, bwbarrett commented on include/nccl_ofi_cuda.h
> +#pragma weak cuFlushGPUDirectRDMAWrites
why?  the current way matches what NCCL does, which seems like a much better path forward.

2024-04-09 20:23 UTC, closed without merging

2024-04-09 20:23 UTC, aws-nslick commented
Dropping