tuner model: do not use channels in bw computation
aws/aws-ofi-nccl pull request #401
Opened 2024-04-26 17:57 UTC by rauteric

* Do not include channels in bw computation -- The current use of nChannels==8 suggests 8x the bw we actually have

* Divide ring bw by 2 (matching the bw computation for NVLSTree and Tree)

Needs perf testing.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-04-26 18:27 UTC, bwbarrett requested changes

2024-04-26 18:27 UTC, bwbarrett commented on src/tuner/nccl_ofi_model.c
> +			bw = (params->internode_bw * params->num_rails) / 2;
This divide by 2 is really confusing.  It's trying to cover for the around the ring twice, but really we need to just refactor the code so the algorithm isn't a mess to figure out.

2024-04-29 21:44 UTC, rauteric commented on src/tuner/nccl_ofi_model.c
> +			bw = NCCL_OFI_MIN(params->intranode_bw, (params->internode_bw * params->num_rails) / 2);
This change (removing the `num_channels` parameter from bw for NVLS_TREE) causes a large deviation from observations for NVLSTree at large message sizes. We need to understand why.

2024-04-29 23:15 UTC, rajachan commented on src/tuner/nccl_ofi_model.c
> -			bw = params->internode_bw * params->num_rails * ofi_nccl_tuner_num_channels();
Credit where it's due: Just remembered @liralon had caught this during an internal review of the tuner, but it got lost.

2024-05-01 04:28 UTC, closed without merging

2024-05-01 04:28 UTC, rauteric commented
Closing in favor of #402, which does not include the `num_channels` removal.