Log prov_errno number in case of completion errors
aws/aws-ofi-nccl pull request #460
Opened 2024-06-26 21:59 UTC by AmedeoSapio

When there is a completion error, the plugin is calling fi_cq_strerror() to get a string message corresponding to the specific error. However, there are errors that are not recognized by libfabric, and that function will just return "Unknown error". This PR is adding the prov_errno value, together with the string representation, to the error log statement, to make it easier to debug such cases.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-26 23:07 UTC, AmedeoSapio commented
bot:aws:retest

2024-06-27 01:33 UTC, rauteric approved these changes

2024-06-27 03:04 UTC, bwbarrett requested changes

2024-06-27 03:04 UTC, bwbarrett commented on src/nccl_ofi_rdma.c
> +	NCCL_OFI_WARN("Request %p completed with error. RC: %d. Error: %s (%d). Completed length: %ld, Request: %s",
Let's format this as `RC: %d.  Error: %d (%s)`.  Much easier for customers to write log parsers for (and many write log parsers).

2024-06-28 19:08 UTC, bwbarrett approved these changes

2024-06-28 19:27 UTC, merged