api: cxx: avoid mid-function initiializers
aws/aws-ofi-nccl pull request #564
Opened 2024-09-04 16:44 UTC by aws-nslick

api: cxx: avoid mid-function initiializers

c++ suppoorts initializers anywhere in the function, but one must not
jump over an initializer with any goto usage. Given the lack of RAII in
C, this becomes a significant painpoint.

Avoid naming these casts, such that the jmp's are acceptable in both cxx
and c.

2024-09-04 18:38 UTC, bwbarrett requested changes

2024-09-04 18:38 UTC, bwbarrett commented on src/nccl_ofi_api.c
>  	}
Please address https://github.com/aws/aws-ofi-nccl/pull/521/commits/cb3caf02bf025f81b959551a2ce2d5afd89565ee#r1714620332

2024-09-09 18:18 UTC, aws-nslick commented
bot:aws:retest

2024-09-17 23:39 UTC, aws-nslick commented
This was squashed into https://github.com/aws/aws-ofi-nccl/pull/563

2024-09-17 23:39 UTC, closed without merging