rdma: add option to round robin the ctrl msg
aws/aws-ofi-nccl pull request #668
Opened 2024-10-18 21:08 UTC by AmedeoSapio

PR https://github.com/aws/aws-ofi-nccl/pull/543 has moved the control message to its own dedicated
endpoint on a single rail. As a result, the control message is not sent on
all rails in a round-robin fashion anymore. This has impacted performance
in some cases, so this is adding an environment variable to optionally enable
the separate control message endpoint, but for now we use as a default the old
behavior of sending the control message round-robining across rails.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-10-18 21:23 UTC, bwbarrett requested changes

2024-10-18 21:23 UTC, bwbarrett commented on src/nccl_ofi_rdma.c
> +	if (!ofi_nccl_rdma_rr_ctrl_msg()) {
we should not call param retrieval code in the critical path.

2024-10-18 21:23 UTC, bwbarrett commented on src/nccl_ofi_rdma.c
> +	if (!ofi_nccl_rdma_rr_ctrl_msg()) {
this patch doesn't do what we talked about.  I expected to see a patch that had num_rails control eps, but it looks like we're back to using the same endpoint for both data and control messages, which breaks Eric's work to use GPU buffers for eager bounce buffers.

2024-10-23 01:13 UTC, AmedeoSapio commented
Closing in favor of #673

2024-10-23 01:13 UTC, closed without merging