Update efa-env-var.md
aws/aws-ofi-nccl pull request #760
Opened 2024-12-31 00:20 UTC by KeitaW

Making it consistent with https://github.com/aws-samples/awsome-distributed-training/blob/main/1.architectures/efa-cheatsheet.md

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2025-01-06 17:32 UTC, rajachan commented
Thanks for the PR @KeitaW. Since the time we folded this file into the repo.. we have made some improvements to the projects wiki pages and all the environment variables are documented here: https://github.com/aws/aws-ofi-nccl/wiki/Environment-Variables . A cheatsheet style doc like what's here is bound to get stale (it already is, with incorrect recommendations and missing tunables). IMO, the wiki is the best place to capture all configurations and I am in favor of removing this file altogether. I can move the contents into the wiki if you agree.

2025-01-06 17:32 UTC, rajachan requested changes
Thanks for the PR @KeitaW. Since the time we folded this file into the repo.. we have made some improvements to the projects wiki pages and all the environment variables are documented here: https://github.com/aws/aws-ofi-nccl/wiki/Environment-Variables . A cheatsheet style doc like what's here is bound to get stale (it already is, with incorrect recommendations and missing tunables). IMO, the wiki is the best place to capture all configurations and I am in favor of removing this file altogether. I can move the contents into the wiki if you agree.

2025-01-06 22:16 UTC, aws-nslick commented
unfortunately unless you're a team member you cannot push to it or submit PRs on those, but want to note here for others that github supports editing the wiki pages locally:

```
aws-ofi-nccl.wiki on  master [?] 
❯ git rev-list --all
1a38c65e376751bf5f41378ee79fbec0552637aa
1a7b16347291974a515e930496082cecc2cae7df
f8104e3fa4ab77b63e9d85e6adb2da0ce9a09286
de297662553dab93a4d9d41ff66c4ab06edabf0b
dce70c4b358112e8c733088202ce82421bee90fe
d6485f3d0363b13144e797eec633d1deb371606f
c587642e2ee9e5e1a6c71a479ca1fcb1b3355ddb
47581c73baefd3238ac89ae2b4ec9b872da278bc
10b09bad5596ea8653b4e80d91b7b6945dc388c4
bda4d469dce95d8f23fd85c5b79c47ac4b2989b4
b6232d9185d63bc59a3071ace1c858da99deea13
befc654e11e47572d40524d7e63680b18f3aa014
633a57dc32aebc2cd27338b634cfe5dd4391a9c9
b69ff42b99be8be075fb6e757b6e03f714c1a003
fef45007c0e560ffb45ba776aae09f738b9240f3
048cbeb331a5345cd1707fc4559935ecaf8f3d8d
506b405bb2d49655fcc2d0374fc1c593eb9a41d6
092daf8e6c84a8f2b55ee531c9f6693af0d2a3b1
8b49c87dd4ea575dc8c5032922bbbf44fbb44429
cc7a06e08c66cc589403152547d85e4cdb53ad63
42d39a63e46a9fe5e70c64c7c6fab6d251e4fc1d
aws-ofi-nccl.wiki on  master [?] 
❯ git remote -v             
origin	https://github.com/aws/aws-ofi-nccl.wiki.git (fetch)
origin	https://github.com/aws/aws-ofi-nccl.wiki.git (push)
```

I wonder what happens if you make the doc folder on the main repo into a git submodule, pointing to this url?

2025-01-22 06:22 UTC, KeitaW commented
Sorry for the late reply and thank you very much for your feedback. I agree with you that  the wiki page is the right place to concentrate the information. If you could add the info in the PR to the wiki as well, that would be awesome.

2025-02-14 00:28 UTC, rajachan commented
I have folded the efa-env-var.md content into a new section [here](https://github.com/aws/aws-ofi-nccl/wiki/Environment-Variables#libfabric-runtime-configurations-for-efa), and really the only two I left on there are the note on `FI_EFA_USE_HUGE_PAGE` and `FI_EFA_FORK_SAFE`. But even `FI_EFA_FORK_SAFE` has been in the plugin for the last ~3 years of releases (since v1.6) that things should work out of the box. Some of the _Sample Presets_ are also really just saying that on a reasonably new version of the plugin the right things should happen, so left those out.  Will create a new PR to clean up the directory.

2025-02-14 00:28 UTC, closed without merging

2025-02-14 00:31 UTC, rajachan commented
On @aws-nslick's suggestion, yep we can use the wiki URL with git (we'll have to use the SSH endpoint though). Wiki as submodule should work and I see some actions that push automatically, but at that point we lose the benefit of out-of-band wiki updates.

2025-02-14 00:47 UTC, KeitaW commented
Thank you @rajachan! Further appreciate you could also check 'NCCL_SHM_USE_CUDA_MEMCPY' as well.